min_pkg = {
    '__extras': {'algorithm': u'',
                 'checksum': u'',
                 'direct_download_URL': None,
                 'discipline_field': u'',
                 'discipline_field_langs': u'fi',
                 'evdescr': [],
                 'evwhen': [],
                 'evwho': [],
                 'mimetype': u'',
                 'pkg_name': u''},
    'access_application_URL': u'https://remsdemo.csc.fi/web/guest/catalogue',
    'availability': u'access_application',
    'contact_URL': u'http://www.csc.fi',
    'contact_phone': u'+256346357',
    'evdescr': [],
    'evtype': [{'value': u'collection'}],
    'evwhen': [],
    'evwho': [],
    'extras': [{'key': 'access_application_URL',
                'value': u'https://remsdemo.csc.fi/web/guest/catalogue'},
               {'key': 'availability', 'value': u'access_application'},
               {'key': 'contact_URL', 'value': u'http://www.csc.fi'},
               {'key': 'contact_phone', 'value': u'+256346357'},
               {'key': 'langdis', 'value': u'False'},
               {'key': 'language', 'value': u'fin'},
               {'key': 'owner', 'value': u'Juho Lehtonen'},
               {'key': 'projdis', 'value': u'True'},
               {'key': 'project_funder', 'value': u''},
               {'key': 'project_funding', 'value': u''},
               {'key': 'project_homepage', 'value': u''},
               {'key': 'project_name', 'value': u''},
               {'key': 'temporal_coverage_begin', 'value': u''},
               {'key': 'temporal_coverage_end', 'value': u''},
               {'key': 'version_PID',
                'value': u'urn:nbn:fi:csc-kata20140215111559034596'},
               {'key': 'evtype_0', 'value': u'collection'},
               {'key': 'title_0', 'value': u'Kata-REMS-testi-2'},
               {'key': 'lang_title_0', 'value': u'fin'},
               {'key': 'title_1', 'value': u'Kata-REMS-test-2'},
               {'key': 'lang_title_1', 'value': u'eng'},
               {'key': 'author_0', 'value': u'CSC'},
               {'key': 'organization_0', 'value': u'CSC'},
               {'key': 'author_0', 'value': u'Lehtonen, Juho'},
               {'key': 'organization_0', 'value': u'CSC'}],
    'id': u'urn:nbn:fi:csc-kata20140215111559029318',
    'langdis': u'False',
    'langtitle': [{'lang': u'fi', 'value': u'Kata-REMS-testi-2'},
                  {'lang': u'en', 'value': u'Kata-REMS-test-2'}],
    'language': u'fin',
    'license_id': u'cc-zero',
    'maintainer': u'Juho Lehtonen',
    'maintainer_email': u'kata.tester@funet.fi',
    'name': 'urn:nbn:fi:csc-kata20140215111559029489',
    'notes': u'',
    'orgauth': [{'org': u'CSC', 'value': u'Lehtonen, Juho'}],
    'owner': u'Juho Lehtonen',
    'projdis': u'True',
    'project_funder': u'',
    'project_funding': u'',
    'project_homepage': u'',
    'project_name': u'',
    'resources': [{'algorithm': u'',
                   'hash': u'',
                   'mimetype': u'',
                   'resource_type': u'dataset',
                   'url': u'http://'}],
    'tag_string': u'rems,testi',
    'tags': [{'name': u'rems'}, {'name': u'testi'}],
    'temporal_coverage_begin': u'',
    'temporal_coverage_end': u'',
    'title': u'urn:nbn:fi:csc-kata20140215111559029489',
    'type': u'dataset',
    'version': u'2014-02-27T10:04:05Z',
    'version_PID': u'urn:nbn:fi:csc-kata20140215111559034596'
}