test_package = {
    'access_application_URL': u'',
    'access_request_URL': u'http://www.fsd.uta.fi/fi/aineistot/jatkokaytto/tilaus.html',
    'algorithm': u'',
    'availability': u'access_request',
    'contact_URL': u'http://www.fsd.uta.fi/',
    'contact_phone': u'',
    'direct_download_URL': u'http://',
    'discipline': u'kunnallistiede,politiikantutkimus',
    'events': [({
                    'key': u'evtype_0',
                    'value': u'collection'},
                {
                    'key': u'evwho_0',
                    'value': u'Borg, Sami; Suomen Gallup'},
                {
                    'key': u'evwhen_0',
                    'value': u'1996-10'},
                {
                    'key': u'evdescr_0',
                    'value': u'Event automatically created at import.'}),
               ({
                    'key': u'evtype_1',
                    'value': u'creation'},
                {
                    'key': u'evwho_1',
                    'value': u'Borg, Sami'},
                {
                    'key': u'evwhen_1',
                    'value': u'1996'},
                {
                    'key': u'evdescr_1',
                    'value': u'Event automatically created at import.'})],
    'geographic_coverage': u'Suomi',
    'groups': [],
    u'id': u'urn:nbn:fi:csc-kata20140214223034685721',
    'langdis': u'True',
    'langtitle': [{'lang': u'',
                   'value': u'Puolueet ja kunnallisdemokratia 1996: yhdistetty aineisto'},
                  {'lang': u'eng',
                   'value': u'Parties and Local Democracy 1996: Combined Data'}],
    'language': u'',
    'license_URL': u'\n Aineistoa luovutetaan tieteelliseen tutkimus- ja opetusk\xe4ytt\xf6\xf6n; FSD:n lupamenettely. \n Tutkimusaineisto on merkitt\xe4v\xe4 l\xe4hdeviitteisiin kaikissa julkaisuissa, joissa aineistoa tai sen osaa k\xe4ytet\xe4\xe4n. Tietoarkiston antaman malliviittaustiedon voi merkit\xe4 l\xe4hdeluetteloon sellaisenaan tai sit\xe4 voi muokata julkaisun k\xe4yt\xe4nt\xf6jen mukaisesti. \n Arkistolle tulee l\xe4hett\xe4\xe4 tiedot julkaisuista, joissa aineiston kopiota tai siit\xe4 luvallisesti otettuja kopioita on hy\xf6dynnetty. \n Aineiston arkistoon luovuttajilla ja arkistolla ei ole vastuuta aineiston uudisk\xe4yt\xf6ss\xe4 tuotetuista tuloksista ja tulkinnoista. \n',
    u'license_id': u'other_closed',
    'license_title': u'other_closed',
    u'maintainer': u'Yhteiskuntatieteellinen tietoarkisto',
    u'maintainer_email': u'fsd@uta.fi',
    'metadata_created': '2014-02-14T20:30:34.721435',
    'metadata_modified': '2014-02-14T20:30:34.721435',
    'mimetype': None,

    u'notes': u'Aineisto on Puolueet ja kunnallisdemokratia 1996 -osa-aineistoista (FSD1021, FSD1022, FSD1023) yhdistetty aineisto. Aineisto sis\xe4lt\xe4\xe4 my\xf6s muuttujan, jossa on eritelty vaaleissa l\xe4pip\xe4\xe4sseet valtuutetut.',
    'num_resources': 3,
    'num_tags': 25,
    'orgauth': [{'org': u'Tampereen yliopisto',
                 'value': u'Borg, Sami'}],
    'owner': u'Borg, Sami',
    u'owner_org': None,
    u'private': False,
    'projdis': u'True',
    'project_funder': u'',
    'project_funding': u'',
    'project_homepage': u'',
    'project_name': u'',
    'relationships_as_object': [],
    'relationships_as_subject': [],
    'resources': [
    {u'algorithm': u'MD5', u'cache_last_updated': None, u'cache_url': None,
     u'created': '2014-02-14T22:30:34.855147',
     u'description': u'Original metadata record', u'format': u'XML',
     u'hash': u'f60e586509d99944e2d62f31979a802f',
     u'id': u'871076bd-ff59-4cbb-8245-bee567462191', u'last_modified': None,
     u'mimetype': None, u'mimetype_inner': None, u'name': None, u'position': 1,
     u'resource_group_id': u'a603fcb1-416d-440a-b18f-b6a81879f8fe',
     u'resource_type': u'file.upload',
     u'revision_id': u'f1067070-a381-494d-b336-4c447226920a',
     u'revision_timestamp': '2014-02-14T20:30:34.721435', u'size': u'270317',
     u'state': u'active', 'tracking_summary': {'recent': 0, 'total': 0},
     u'url': u'http://', u'webstore_last_updated': None, u'webstore_url': None},
    {u'cache_last_updated': None, u'cache_url': None,
     u'created': '2014-02-14T22:30:34.855156',
     u'description': u'Puolueet ja kunnallisdemokratia 1996: yhdistetty aineisto',
     u'format': u'HTML', u'hash': u'',
     u'id': u'67c64b94-747d-4fee-a67e-e16bfc80f966', u'last_modified': None,
     u'mimetype': None, u'mimetype_inner': None, u'name': None, u'position': 2,
     u'resource_group_id': u'a603fcb1-416d-440a-b18f-b6a81879f8fe',
     u'resource_type': u'documentation',
     u'revision_id': u'f1067070-a381-494d-b336-4c447226920a',
     u'revision_timestamp': '2014-02-14T20:30:34.721435', u'size': None,
     u'state': u'active', 'tracking_summary': {'recent': 0, 'total': 0},
     u'url': u'http://', u'webstore_last_updated': None,
     u'webstore_url': None}],
    u'revision_id': u'f1067070-a381-494d-b336-4c447226920a',
    u'revision_timestamp': '2014-02-14T20:30:34.721435', u'state': u'active',
    'tag_string': u'asenteet ja mielipiteet,demokratia,eduskuntavaalit,edustuksellinen demokratia,hallinto,hallitus,julkiset palvelut,j\xe4rjestelm\xe4t ja organisaatiot,kunnallishallinto,kunnallispolitiikka,kunnallisvaalit,kunnanvaltuustot,kunnat,luottamustoimet,poliittinen k\xe4ytt\xe4ytyminen,poliittinen osallistuminen,poliittinen toiminta,poliittiset asenteet,poliittiset instituutiot,puolueet,puolueiden kannatus,tiedonv\xe4litys,vaalit,vaikuttaminen,\xe4\xe4nest\xe4minen',
    'temporal_coverage_begin': u'1996',
    'temporal_coverage_end': u'1996',
    u'title': u'Puolueet ja kunnallisdemokratia 1996: yhdistetty aineisto',
    'tracking_summary': {'recent': 1, 'total': 1},
    u'type': u'dataset',
    u'url': None,
    u'version': u'1996-00-00',
    'version_PID': u'urn:nbn:fi:csc-kata20140214223034713535'}
